Repository LukaszZachariasz/BitTorrent, pull requests merged in 2020-06, with the labels that each got.

#21 Frontend init structure
  .run/BitTorrentArchitecture.run.xml
  bittorrent-backend/client-backend/src/main/java/com/sonb/client/ClientController.java
  bittorrent-backend/tracker-backend/src/main/java/com/sonb/tracker/TrackerController.java
  bittorrent-simulator/.browserslistrc
  bittorrent-simulator/angular.json
  bittorrent-simulator/e2e/tsconfig.json
  bittorrent-simulator/package-lock.json
  bittorrent-simulator/package.json
  bittorrent-simulator/src/app/app-routing.module.ts
  bittorrent-simulator/src/app/app.component.css
  bittorrent-simulator/src/app/app.component.html
  bittorrent-simulator/src/app/app.component.spec.ts
  bittorrent-simulator/src/app/app.module.ts
  bittorrent-simulator/src/app/components/client-management/client-list/client-list.component.css
  bittorrent-simulator/src/app/components/client-management/client-list/client-list.component.html
  bittorrent-simulator/src/app/components/client-management/client-list/client-list.component.ts
  bittorrent-simulator/src/app/components/client-management/client-management.component.css
  bittorrent-simulator/src/app/components/client-management/client-management.component.html
  bittorrent-simulator/src/app/components/client-management/client-management.component.ts
  bittorrent-simulator/src/app/components/client-management/client-management.module.ts
  bittorrent-simulator/src/app/components/client-management/client/client.component.css
  bittorrent-simulator/src/app/components/client-management/client/client.component.html
  bittorrent-simulator/src/app/components/client-management/client/client.component.ts
  bittorrent-simulator/src/app/components/header/header.component.css
  bittorrent-simulator/src/app/components/header/header.component.html
  bittorrent-simulator/src/app/components/header/header.component.ts
  bittorrent-simulator/src/app/components/tracker-management/tracker-management.component.css
  bittorrent-simulator/src/app/components/tracker-management/tracker-management.component.html
  bittorrent-simulator/src/app/components/tracker-management/tracker-management.component.ts
  bittorrent-simulator/src/app/components/tracker-management/tracker-management.module.ts
  bittorrent-simulator/src/app/constants/client-url.enum.ts
  bittorrent-simulator/src/app/models/client/client.interface.ts
  bittorrent-simulator/src/app/package.json
  bittorrent-simulator/src/app/services/client-list.service.ts
  bittorrent-simulator/src/app/services/services.module.ts
  bittorrent-simulator/src/app/services/tracker.service.ts
  bittorrent-simulator/src/app/shared/loader/loader.component.css
  bittorrent-simulator/src/app/shared/loader/loader.component.html
  bittorrent-simulator/src/app/shared/loader/loader.component.ts
  bittorrent-simulator/src/app/shared/shared.module.ts
  bittorrent-simulator/src/index.html
  bittorrent-simulator/src/main.ts
  bittorrent-simulator/src/styles.css
  bittorrent-simulator/tsconfig.app.json
  bittorrent-simulator/tsconfig.base.json
  bittorrent-simulator/tsconfig.json
  bittorrent-simulator/tsconfig.spec.json
  bittorrent-simulator/tslint.json
Labels: feature

#29 Added progress of download file, improved client-list.component
  .run/BitTorrentArchitecture.run.xml
  bittorrent-simulator/src/app/components/client-management/client-file-list/client-file-list.component.html
  bittorrent-simulator/src/app/components/client-management/client-file-list/client-file-list.component.ts
  bittorrent-simulator/src/app/components/client-management/client-list/client-list.component.html
  bittorrent-simulator/src/app/components/client-management/client-list/client-list.component.ts
  bittorrent-simulator/src/app/components/client-management/client-panel/client-panel.component.html
  bittorrent-simulator/src/app/components/client-management/client-panel/client-panel.component.ts
  bittorrent-simulator/src/app/constants/config-constants.ts
Labels: bugfix, feature

#30 Deny and allow access to file for other clients
  .run/BitTorrentArchitecture.run.xml
  bittorrent-backend/client-backend/src/main/java/com/sonb/client/ClientControlBehavior.java
  bittorrent-backend/client-backend/src/main/java/com/sonb/client/ClientFileDownloader.java
  bittorrent-backend/client-backend/src/main/java/com/sonb/client/ClientManagement.java
  bittorrent-backend/client-backend/src/main/java/com/sonb/client/ClientToTrackerConnector.java
  bittorrent-simulator/src/app/components/client-management/client-file-list/client-file-list.component.html
  bittorrent-simulator/src/app/components/client-management/client-file-list/client-file-list.component.ts
  bittorrent-simulator/src/app/components/client-management/client-list/client-list.component.html
  bittorrent-simulator/src/app/components/client-management/client-management.module.ts
  bittorrent-simulator/src/app/components/client-management/client-panel/client-panel.component.html
  bittorrent-simulator/src/app/constants/urls/client-url.enum.ts
  bittorrent-simulator/src/app/models/client/client-files-info-list.interface.ts
  bittorrent-simulator/src/app/services/client-file.service.ts
Labels: bugfix, feature

#31 Added Possibility to set simulated download time delay
  bittorrent-backend/client-backend/src/main/java/com/sonb/client/ClientController.java
  bittorrent-backend/client-backend/src/main/java/com/sonb/client/ClientService.java
  bittorrent-simulator/src/app/components/client-management/client-management.module.ts
  bittorrent-simulator/src/app/components/client-management/client-panel/client-panel.component.html
  bittorrent-simulator/src/app/components/client-management/client-panel/client-panel.component.ts
  bittorrent-simulator/src/app/services/client-control-behaviour.service.ts
  bittorrent-simulator/src/app/services/client-file.service.ts
  bittorrent-simulator/src/app/services/services.module.ts
Labels: bugfix, feature

#32 Documentation added
  #SPRAWOZDANIE/SONB_2ID22B_ZACHARIASZ_ZAKRZEWSKI_PROJEKT.docx
  #SPRAWOZDANIE/SONB_2ID22B_ZACHARIASZ_ZAKRZEWSKI_PROJEKT.pdf
  README.md
Labels: documentation
